version: '3.8'

services:
  db:
    image: postgres:16
    container_name: diafin_postgres
    ports:
      - "5333:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sag_network
  
volumes:
  postgres-data:
networks:
  sag_network:
    driver: bridge  